### ISSUE TITLE
When I use a customized scheduler Storm does not collect metrics

### ISSUE THREAD

**Issue by felipegutierrez** [staslev/storm-metrics-reporter#5]
Hi, when I use a customized scheduler which implements [IScheduler](https://github.com/apache/storm/blob/master/storm-server/src/main/java/org/apache/storm/scheduler/IScheduler.java) interface I cannot see any metrics on Graphite anymore. I tested without a customized scheduler and it works. However it stops to work when I just configure a customized scheduler on the storm.yaml
```
supervisor.scheduler.meta:
  site: "cluster"
storm.scheduler: "org.sense.storm.scheduler.SiteAwareScheduler"
```

Do you have any hint of what could be happening?
Thanks

**Comment by staslev** [comment]
Hi @felipegutierrez, 

Are you using `storm-metrics-reporter` to get your metrics out to Graphite? Why no star? :)

I must admit I haven't been actively maintaining this project for more than a couple of years now, so I may not be up to date with recent changes introduced to Storm since `1.0`.

Moreover, looks like Storm `1.2` introduced [a new metric system](http://storm.apache.org/releases/2.0.0-SNAPSHOT/index.html), deprecating the old one. 
While I'm not sure whether this has anything to do with the issue you're experiencing, I'm afraid it's just another indication I might not be able to provide much of an assistance on this one - sorry about that.

I'll try to see if I can take a look at it sometime, but unfortunately I can't commit to a concrete timeframe.

-Stas

**Comment by felipegutierrez** [comment]
do you mean [this version](http://storm.apache.org/releases/1.2.2/metrics_v2.html) from 1.2.2? I will move to this one. thanks for your answer.
